export enum Path {
    HOME = '/',
    CONTACT_PAGE = '/contacts',
}

export enum ContentKey {
    LOGO_IMAGE_SRC = 'LOGO_IMAGE_SRC',
    LOGO_IMAGE_ALT = 'LOGO_IMAGE_ALT',
    SEND_MESSAGE_IMAGE_SRC = 'SEND_MESSAGE_IMAGE_SRC',
    SEND_MESSAGE_IMAGE_ALT = 'SEND_MESSAGE_IMAGE_ALT',
    YOUTUBE_VIDEO_LINK = 'YOUTUBE_VIDEO_LINK',
    YOUTUBE_VIDEO_LABEL = 'YOUTUBE_VIDEO_LABEL',
}
